// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"web/app/model/internal"
)

// User is the golang structure for table user.
type User internal.User

// 注册请求参数，用于前后端交互参数格式约定
type UserApiSignUpReq struct {
	Name  string `v:"required|length:6,16#账号不能为空|账号长度应当在:min到:max之间"`
	Password  string `v:"required|length:6,16#密码不能为空|密码长度应当在:min到:max之间"`
	Email  string `v:"required|length:6,16|email#邮箱不能为空|邮箱长度应当在:min到:max之间|邮箱格式不正确"`
	Role  string `v:"required#角色不能为空"`
	Password2 string `v:"required|length:6,16|same:Password#请输入确认密码|密码长度应当在:min到:max之间|两次密码输入不相等"`
}

// 登录请求参数，用于前后端交互参数格式约定
type UserApiSignInReq struct {
	Name string `v:"required#账号不能为空"`
	Password string `v:"required#密码不能为空"`
}

// 账号唯一性检测请求参数，用于前后端交互参数格式约定
type UserApiCheckPassportReq struct {
	Passport string `v:"required#账号不能为空"`
}

// 昵称唯一性检测请求参数，用于前后端交互参数格式约定
type UserApiCheckNickNameReq struct {
	Nickname string `v:"required#昵称不能为空"`
}

// 注册输入参数
type UserServiceSignUpReq struct {
	Passport string
	Password string
	Nickname string
}

// 找回密码email
type UserApiCheckEmail struct {
	Email string `v:"required#邮箱不能为空"`
}
// 重置密码email
type UserApiCheckPassword struct {
	Password string `v:"required|length:6,16#密码不能为空|账号长度应当在:min到:max之间"`
	Token string `v:"required#Token不能为空"`
}
//用户
type UserApiCheckUser struct {
	Id int
	Name string
	Email string
}
